version: '2'

services:
  kennel_card:
    build: .
    volumes:
      - .:/data
      - ./app:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      PASSWORD:
      SHEET:
      FOLDER:
      GOOGLE_CREDENTIALS: "/data/secret.json"
